use chrono::Utc;
use rusqlite::{params, Connection, OptionalExtension};
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize)] #[serde(rename_all="camelCase")] pub struct UpdateClientInput{pub id:i64,pub name:String,pub phone:String,pub birth_date:Option<String>}
#[derive(Debug, Deserialize)] #[serde(rename_all="camelCase")] pub struct UpdateServiceInput{pub id:i64,pub name:String,pub price_cents:i64,pub duration_min:i64}
#[derive(Debug, Deserialize)] #[serde(rename_all="camelCase")] pub struct UpdateStaffInput{pub id:i64,pub name:String,pub phone:Option<String>,pub commission_percent:i64,pub product_commission_percent:i64}
#[derive(Debug, Deserialize)] #[serde(rename_all="camelCase")] pub struct UpdateProductInput{pub id:i64,pub name:String,pub description:Option<String>,pub price_cents:i64}
#[derive(Debug, Deserialize)] #[serde(rename_all="camelCase")] pub struct UpdateCashInput{pub id:i64,pub description:String,pub amount_cents:i64,pub date:String,pub payment_method:Option<String>,pub client_id:Option<i64>,pub staff_id:Option<i64>}
#[derive(Debug, Serialize)] #[serde(rename_all="camelCase")] pub struct RemarketingClient{pub id:i64,pub name:String,pub phone:String,pub last_visit:String,pub days_without_visit:i64,pub total_spent_cents:i64,pub visits:i64}
#[derive(Debug, Serialize)] #[serde(rename_all="camelCase")] pub struct ArchivedItem{pub id:i64,pub name:String,pub kind:String}
#[derive(Debug, Clone, Serialize, Deserialize)] #[serde(rename_all="camelCase")] pub struct WhatsAppSettings{pub enabled:bool,pub api_base_url:String,pub api_version:String,pub phone_number_id:String,pub access_token:String,pub social_links_text:String}
#[derive(Debug, Serialize)] #[serde(rename_all="camelCase")] pub struct WhatsAppSendResult{pub success:bool,pub provider_message_id:String,pub status:String}
#[derive(Debug, Serialize)] #[serde(rename_all="camelCase")] pub struct StaffSettlement{pub id:i64,pub staff_id:i64,pub staff_name:String,pub start_date:String,pub end_date:String,pub gross_cents:i64,pub commission_cents:i64,pub net_cents:i64,pub service_sales:i64,pub product_sales:i64,pub created_at:String}

pub fn ensure_schema(c:&Connection)->Result<(),String>{
 let _=c.execute("ALTER TABLE clients ADD COLUMN active INTEGER NOT NULL DEFAULT 1",[]);
 let _=c.execute("ALTER TABLE cash_transactions ADD COLUMN settlement_id INTEGER",[]);
 let _=c.execute("ALTER TABLE cash_transactions ADD COLUMN stock_movement_id INTEGER",[]);
 c.execute_batch("CREATE TABLE IF NOT EXISTS whatsapp_settings(id INTEGER PRIMARY KEY CHECK(id=1),enabled INTEGER NOT NULL DEFAULT 0,api_base_url TEXT NOT NULL DEFAULT 'https://graph.facebook.com',api_version TEXT NOT NULL DEFAULT 'v23.0',phone_number_id TEXT NOT NULL DEFAULT '',access_token TEXT NOT NULL DEFAULT '',social_links_text TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT ''); INSERT OR IGNORE INTO whatsapp_settings(id) VALUES(1); CREATE TABLE IF NOT EXISTS whatsapp_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,client_id INTEGER,phone TEXT NOT NULL,message_type TEXT NOT NULL,message_text TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',provider_message_id TEXT NOT NULL DEFAULT '',error_text TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,sent_at TEXT NOT NULL DEFAULT '',FOREIGN KEY(client_id) REFERENCES clients(id)); CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_client ON whatsapp_messages(client_id,created_at); CREATE TABLE IF NOT EXISTS staff_settlements(id INTEGER PRIMARY KEY AUTOINCREMENT,staff_id INTEGER NOT NULL,staff_name TEXT NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,gross_cents INTEGER NOT NULL,commission_cents INTEGER NOT NULL,net_cents INTEGER NOT NULL,service_sales INTEGER NOT NULL DEFAULT 0,product_sales INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,FOREIGN KEY(staff_id) REFERENCES staff(id)); CREATE INDEX IF NOT EXISTS idx_staff_settlements_staff ON staff_settlements(staff_id,created_at); CREATE INDEX IF NOT EXISTS idx_cash_settlement ON cash_transactions(settlement_id);").map_err(|e|e.to_string())?;
 Ok(())
}
fn digits(v:&str)->String{v.chars().filter(|c|c.is_ascii_digit()).collect()}
fn valid_pct(v:i64)->Result<(),String>{if(0..=100).contains(&v){Ok(())}else{Err("Percentual deve ficar entre 0 e 100.".into())}}

pub fn update_client(c:&Connection,i:UpdateClientInput)->Result<(),String>{if i.name.trim().is_empty(){return Err("Informe o nome do cliente.".into())}c.execute("UPDATE clients SET name=?1,phone=?2,birth_date=?3 WHERE id=?4",params![i.name.trim(),digits(&i.phone),i.birth_date.unwrap_or_default(),i.id]).map_err(|e|e.to_string())?;Ok(())}
pub fn set_client_active(c:&Connection,id:i64,active:bool)->Result<(),String>{ensure_schema(c)?;c.execute("UPDATE clients SET active=?1 WHERE id=?2",params![if active{1}else{0},id]).map_err(|e|e.to_string())?;Ok(())}
pub fn delete_client_safe(c:&Connection,id:i64)->Result<(),String>{let refs:i64=c.query_row("SELECT (SELECT COUNT(*) FROM appointments WHERE client_id=?1)+(SELECT COUNT(*) FROM cash_transactions WHERE client_id=?1)",params![id],|r|r.get(0)).map_err(|e|e.to_string())?;if refs>0{return Err("Este cliente possui histórico. Arquive em vez de excluir.".into())}c.execute("DELETE FROM clients WHERE id=?1",params![id]).map_err(|e|e.to_string())?;Ok(())}
pub fn update_service(c:&Connection,i:UpdateServiceInput)->Result<(),String>{if i.name.trim().is_empty()||i.price_cents<=0||i.duration_min<=0{return Err("Nome, preço e duração válidos são obrigatórios.".into())}c.execute("UPDATE services SET name=?1,price_cents=?2,duration_min=?3 WHERE id=?4",params![i.name.trim(),i.price_cents,i.duration_min,i.id]).map_err(|e|e.to_string())?;Ok(())}
pub fn set_service_active(c:&Connection,id:i64,active:bool)->Result<(),String>{c.execute("UPDATE services SET active=?1 WHERE id=?2",params![if active{1}else{0},id]).map_err(|e|e.to_string())?;Ok(())}
pub fn delete_service_safe(c:&Connection,id:i64)->Result<(),String>{let refs:i64=c.query_row("SELECT COUNT(*) FROM appointment_services WHERE service_id=?1",params![id],|r|r.get(0)).map_err(|e|e.to_string())?;if refs>0{return Err("Serviço já utilizado. Arquive em vez de excluir.".into())}c.execute("DELETE FROM staff_service_commissions WHERE service_id=?1",params![id]).map_err(|e|e.to_string())?;c.execute("DELETE FROM services WHERE id=?1",params![id]).map_err(|e|e.to_string())?;Ok(())}
pub fn update_staff(c:&Connection,i:UpdateStaffInput)->Result<(),String>{valid_pct(i.commission_percent)?;valid_pct(i.product_commission_percent)?;if i.name.trim().is_empty(){return Err("Informe o nome do colaborador.".into())}c.execute("UPDATE staff SET name=?1,phone=?2,commission_percent=?3,product_commission_percent=?4 WHERE id=?5",params![i.name.trim(),i.phone.unwrap_or_default(),i.commission_percent,i.product_commission_percent,i.id]).map_err(|e|e.to_string())?;Ok(())}
pub fn set_staff_active(c:&Connection,id:i64,active:bool)->Result<(),String>{c.execute("UPDATE staff SET active=?1 WHERE id=?2",params![if active{1}else{0},id]).map_err(|e|e.to_string())?;Ok(())}
pub fn delete_staff_safe(c:&Connection,id:i64)->Result<(),String>{ensure_schema(c)?;let refs:i64=c.query_row("SELECT (SELECT COUNT(*) FROM appointments WHERE staff_id=?1)+(SELECT COUNT(*) FROM cash_transactions WHERE staff_id=?1)+(SELECT COUNT(*) FROM staff_settlements WHERE staff_id=?1)",params![id],|r|r.get(0)).map_err(|e|e.to_string())?;if refs>0{return Err("Colaborador possui histórico. Arquive em vez de excluir.".into())}c.execute("DELETE FROM staff_service_commissions WHERE staff_id=?1",params![id]).map_err(|e|e.to_string())?;c.execute("DELETE FROM staff WHERE id=?1",params![id]).map_err(|e|e.to_string())?;Ok(())}
pub fn update_product(c:&Connection,i:UpdateProductInput)->Result<(),String>{if i.name.trim().is_empty()||i.price_cents<=0{return Err("Nome e preço válidos são obrigatórios.".into())}c.execute("UPDATE products SET name=?1,description=?2,price_cents=?3 WHERE id=?4",params![i.name.trim(),i.description.unwrap_or_default(),i.price_cents,i.id]).map_err(|e|e.to_string())?;Ok(())}
pub fn set_product_active(c:&Connection,id:i64,active:bool)->Result<(),String>{c.execute("UPDATE products SET active=?1 WHERE id=?2",params![if active{1}else{0},id]).map_err(|e|e.to_string())?;Ok(())}
pub fn delete_product_safe(c:&Connection,id:i64)->Result<(),String>{let refs:i64=c.query_row("SELECT COUNT(*) FROM stock_movements WHERE product_id=?1",params![id],|r|r.get(0)).map_err(|e|e.to_string())?;if refs>0{return Err("Produto possui movimentações de estoque. Arquive em vez de excluir.".into())}c.execute("DELETE FROM products WHERE id=?1",params![id]).map_err(|e|e.to_string())?;Ok(())}

pub fn archived_items(c:&Connection,kind:&str)->Result<Vec<ArchivedItem>,String>{ensure_schema(c)?;let (table,name_col)=match kind{"client"=>("clients","name"),"service"=>("services","name"),"staff"=>("staff","name"),"product"=>("products","name"),_=>return Err("Tipo de arquivo inválido.".into())};let sql=format!("SELECT id,{} FROM {} WHERE active=0 ORDER BY {} COLLATE NOCASE",name_col,table,name_col);let mut s=c.prepare(&sql).map_err(|e|e.to_string())?;let rows=s.query_map([],|r|Ok(ArchivedItem{id:r.get(0)?,name:r.get(1)?,kind:kind.to_string()})).map_err(|e|e.to_string())?;rows.collect::<Result<Vec<_>,_>>().map_err(|e|e.to_string())}
pub fn restore_archived(c:&Connection,kind:&str,id:i64)->Result<(),String>{ensure_schema(c)?;let table=match kind{"client"=>"clients","service"=>"services","staff"=>"staff","product"=>"products",_=>return Err("Tipo de arquivo inválido.".into())};let sql=format!("UPDATE {} SET active=1 WHERE id=?1",table);c.execute(&sql,params![id]).map_err(|e|e.to_string())?;Ok(())}

pub fn update_cash_manual(c:&Connection,i:UpdateCashInput)->Result<(),String>{ensure_schema(c)?;let(source,sale_type,settlement_id):(String,String,Option<i64>)=c.query_row("SELECT source,sale_type,settlement_id FROM cash_transactions WHERE id=?1",params![i.id],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).map_err(|_|"Lançamento não encontrado.".to_string())?;if settlement_id.is_some(){return Err("Este lançamento faz parte de um fechamento. Reabra o fechamento antes de editar.".into())}if source!="manual"||sale_type=="product"{return Err("Este lançamento afeta atendimento ou estoque. Exclua o lançamento para corrigir.".into())}if i.amount_cents<=0{return Err("Valor deve ser maior que zero.".into())}let(staff_name,pct):(String,i64)=if let Some(id)=i.staff_id{c.query_row("SELECT name,commission_percent FROM staff WHERE id=?1",params![id],|r|Ok((r.get(0)?,r.get(1)?))).map_err(|_|"Colaborador inválido.".to_string())?}else{(String::new(),0)};let effective=if i.staff_id.is_some()&&sale_type=="service"{pct}else{0};let commission=i.amount_cents*effective/100;let net=i.amount_cents-commission;c.execute("UPDATE cash_transactions SET description=?1,amount_cents=?2,date=?3,payment_method=?4,client_id=?5,staff_id=?6,staff_name=?7,commission_percent=?8,commission_cents=?9,net_cents=?10 WHERE id=?11",params![i.description,i.amount_cents,i.date,i.payment_method.unwrap_or_default(),i.client_id,i.staff_id,staff_name,effective,commission,net,i.id]).map_err(|e|e.to_string())?;Ok(())}

pub fn delete_cash_transaction(c:&Connection,id:i64)->Result<(),String>{ensure_schema(c)?;let row:(String,String,String,Option<i64>,Option<i64>,Option<i64>)=c.query_row("SELECT source,sale_type,description,appointment_id,settlement_id,stock_movement_id FROM cash_transactions WHERE id=?1",params![id],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?,r.get(3)?,r.get(4)?,r.get(5)?))).map_err(|_|"Lançamento não encontrado.".to_string())?;if row.4.is_some(){return Err("Este lançamento já está em um fechamento. Reabra o fechamento antes de excluir.".into())}let tx=c.unchecked_transaction().map_err(|e|e.to_string())?;if row.1=="product"{
    let movement:Option<(i64,i64,i64)>=if let Some(movement_id)=row.5{
        tx.query_row("SELECT id,product_id,quantity FROM stock_movements WHERE id=?1",params![movement_id],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).optional().map_err(|e|e.to_string())?
    } else {
        let note=format!("Venda no caixa — {}",row.2);
        tx.query_row("SELECT id,product_id,quantity FROM stock_movements WHERE note=?1 AND quantity<0 ORDER BY id DESC LIMIT 1",params![note],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).optional().map_err(|e|e.to_string())?
    };
    if let Some((movement_id,product_id,quantity))=movement{tx.execute("UPDATE products SET stock=stock+?1 WHERE id=?2",params![-quantity,product_id]).map_err(|e|e.to_string())?;tx.execute("DELETE FROM stock_movements WHERE id=?1",params![movement_id]).map_err(|e|e.to_string())?;}
}if row.0=="atendimento"{if let Some(appointment_id)=row.3{tx.execute("UPDATE appointments SET status='Confirmado',payment_method='',cash_transaction_id=NULL WHERE id=?1",params![appointment_id]).map_err(|e|e.to_string())?;}}tx.execute("DELETE FROM cash_transactions WHERE id=?1",params![id]).map_err(|e|e.to_string())?;tx.commit().map_err(|e|e.to_string())?;Ok(())}

pub fn create_staff_settlement(c:&Connection,staff_id:i64,start_date:&str,end_date:&str)->Result<StaffSettlement,String>{ensure_schema(c)?;if start_date>end_date{return Err("Período de fechamento inválido.".into())}let staff_name:String=c.query_row("SELECT name FROM staff WHERE id=?1",params![staff_id],|r|r.get(0)).map_err(|_|"Colaborador não encontrado.".to_string())?;let(gross,commission,service_sales,product_sales,count):(i64,i64,i64,i64,i64)=c.query_row("SELECT COALESCE(SUM(amount_cents),0),COALESCE(SUM(commission_cents),0),COALESCE(SUM(CASE WHEN sale_type='service' THEN 1 ELSE 0 END),0),COALESCE(SUM(CASE WHEN sale_type='product' THEN 1 ELSE 0 END),0),COUNT(*) FROM cash_transactions WHERE staff_id=?1 AND kind='entrada' AND date BETWEEN ?2 AND ?3 AND settlement_id IS NULL",params![staff_id,start_date,end_date],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?,r.get(3)?,r.get(4)?))).map_err(|e|e.to_string())?;if count==0{return Err("Não existem lançamentos em aberto para este colaborador no período.".into())}let net=gross-commission;let created=Utc::now().to_rfc3339();let tx=c.unchecked_transaction().map_err(|e|e.to_string())?;tx.execute("INSERT INTO staff_settlements(staff_id,staff_name,start_date,end_date,gross_cents,commission_cents,net_cents,service_sales,product_sales,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10)",params![staff_id,staff_name,start_date,end_date,gross,commission,net,service_sales,product_sales,created]).map_err(|e|e.to_string())?;let settlement_id=tx.last_insert_rowid();tx.execute("UPDATE cash_transactions SET settlement_id=?1 WHERE staff_id=?2 AND kind='entrada' AND date BETWEEN ?3 AND ?4 AND settlement_id IS NULL",params![settlement_id,staff_id,start_date,end_date]).map_err(|e|e.to_string())?;tx.commit().map_err(|e|e.to_string())?;Ok(StaffSettlement{id:settlement_id,staff_id,staff_name,start_date:start_date.into(),end_date:end_date.into(),gross_cents:gross,commission_cents:commission,net_cents:net,service_sales,product_sales,created_at:created})}
pub fn list_staff_settlements(c:&Connection,staff_id:i64)->Result<Vec<StaffSettlement>,String>{ensure_schema(c)?;let mut s=c.prepare("SELECT id,staff_id,staff_name,start_date,end_date,gross_cents,commission_cents,net_cents,service_sales,product_sales,created_at FROM staff_settlements WHERE staff_id=?1 ORDER BY id DESC LIMIT 100").map_err(|e|e.to_string())?;let rows=s.query_map(params![staff_id],|r|Ok(StaffSettlement{id:r.get(0)?,staff_id:r.get(1)?,staff_name:r.get(2)?,start_date:r.get(3)?,end_date:r.get(4)?,gross_cents:r.get(5)?,commission_cents:r.get(6)?,net_cents:r.get(7)?,service_sales:r.get(8)?,product_sales:r.get(9)?,created_at:r.get(10)?})).map_err(|e|e.to_string())?;rows.collect::<Result<Vec<_>,_>>().map_err(|e|e.to_string())}
pub fn reopen_staff_settlement(c:&Connection,id:i64)->Result<(),String>{ensure_schema(c)?;let tx=c.unchecked_transaction().map_err(|e|e.to_string())?;let exists:i64=tx.query_row("SELECT COUNT(*) FROM staff_settlements WHERE id=?1",params![id],|r|r.get(0)).map_err(|e|e.to_string())?;if exists==0{return Err("Fechamento não encontrado.".into())}tx.execute("UPDATE cash_transactions SET settlement_id=NULL WHERE settlement_id=?1",params![id]).map_err(|e|e.to_string())?;tx.execute("DELETE FROM staff_settlements WHERE id=?1",params![id]).map_err(|e|e.to_string())?;tx.commit().map_err(|e|e.to_string())?;Ok(())}

pub fn remarketing_clients(c:&Connection,minimum_days:i64,reference_date:&str)->Result<Vec<RemarketingClient>,String>{ensure_schema(c)?;let mut s=c.prepare("SELECT c.id,c.name,c.phone,COALESCE(MAX(CASE WHEN ct.kind='entrada' AND ct.sale_type='service' THEN ct.date END),''),CAST(julianday(?2)-julianday(COALESCE(MAX(CASE WHEN ct.kind='entrada' AND ct.sale_type='service' THEN ct.date END),date(c.created_at))) AS INTEGER),COALESCE(SUM(CASE WHEN ct.kind='entrada' THEN ct.amount_cents ELSE 0 END),0),COALESCE(SUM(CASE WHEN ct.kind='entrada' AND ct.sale_type='service' THEN 1 ELSE 0 END),0) FROM clients c LEFT JOIN cash_transactions ct ON ct.client_id=c.id WHERE COALESCE(c.active,1)=1 GROUP BY c.id,c.name,c.phone,c.created_at HAVING CAST(julianday(?2)-julianday(COALESCE(MAX(CASE WHEN ct.kind='entrada' AND ct.sale_type='service' THEN ct.date END),date(c.created_at))) AS INTEGER)>=?1 ORDER BY 5 DESC,c.name").map_err(|e|e.to_string())?;let rows=s.query_map(params![minimum_days,reference_date],|r|Ok(RemarketingClient{id:r.get(0)?,name:r.get(1)?,phone:r.get(2)?,last_visit:r.get(3)?,days_without_visit:r.get(4)?,total_spent_cents:r.get(5)?,visits:r.get(6)?})).map_err(|e|e.to_string())?;rows.collect::<Result<Vec<_>,_>>().map_err(|e|e.to_string())}

pub fn get_whatsapp_settings(c:&Connection)->Result<WhatsAppSettings,String>{ensure_schema(c)?;c.query_row("SELECT enabled,api_base_url,api_version,phone_number_id,access_token,social_links_text FROM whatsapp_settings WHERE id=1",[],|r|Ok(WhatsAppSettings{enabled:r.get::<_,i64>(0)?!=0,api_base_url:r.get(1)?,api_version:r.get(2)?,phone_number_id:r.get(3)?,access_token:r.get(4)?,social_links_text:r.get(5)?})).map_err(|e|e.to_string())}
pub fn save_whatsapp_settings(c:&Connection,s:WhatsAppSettings)->Result<WhatsAppSettings,String>{ensure_schema(c)?;c.execute("UPDATE whatsapp_settings SET enabled=?1,api_base_url=?2,api_version=?3,phone_number_id=?4,access_token=?5,social_links_text=?6,updated_at=?7 WHERE id=1",params![if s.enabled{1}else{0},s.api_base_url.trim(),s.api_version.trim(),s.phone_number_id.trim(),s.access_token.trim(),s.social_links_text,Utc::now().to_rfc3339()]).map_err(|e|e.to_string())?;get_whatsapp_settings(c)}
pub fn send_whatsapp_text(c:&Connection,client_id:Option<i64>,phone:String,message_type:String,text:String)->Result<WhatsAppSendResult,String>{ensure_schema(c)?;let settings=get_whatsapp_settings(c)?;let phone=digits(&phone);if phone.is_empty(){return Err("Telefone do cliente não informado.".into())}let created=Utc::now().to_rfc3339();c.execute("INSERT INTO whatsapp_messages(client_id,phone,message_type,message_text,status,created_at) VALUES(?1,?2,?3,?4,'pending',?5)",params![client_id,phone,message_type,text,created]).map_err(|e|e.to_string())?;let log_id=c.last_insert_rowid();if !settings.enabled{return Err("WhatsApp API está desativada em Configurações.".into())}if settings.phone_number_id.trim().is_empty()||settings.access_token.trim().is_empty(){return Err("Configure Phone Number ID e Access Token do WhatsApp Cloud API.".into())}let url=format!("{}/{}/{}/messages",settings.api_base_url.trim_end_matches('/'),settings.api_version.trim_matches('/'),settings.phone_number_id.trim());let payload=serde_json::json!({"messaging_product":"whatsapp","recipient_type":"individual","to":phone,"type":"text","text":{"preview_url":false,"body":text}});let client=reqwest::blocking::Client::new();match client.post(url).bearer_auth(settings.access_token).json(&payload).send(){Ok(resp)=>{let status=resp.status();let body:serde_json::Value=resp.json().unwrap_or_else(|_|serde_json::json!({}));if status.is_success(){let mid=body.get("messages").and_then(|v|v.get(0)).and_then(|v|v.get("id")).and_then(|v|v.as_str()).unwrap_or("").to_string();c.execute("UPDATE whatsapp_messages SET status='sent',provider_message_id=?1,sent_at=?2 WHERE id=?3",params![mid,Utc::now().to_rfc3339(),log_id]).map_err(|e|e.to_string())?;Ok(WhatsAppSendResult{success:true,provider_message_id:mid,status:"sent".into()})}else{let err=body.to_string();let _=c.execute("UPDATE whatsapp_messages SET status='failed',error_text=?1 WHERE id=?2",params![err,log_id]);Err(format!("WhatsApp API recusou o envio: {}",status))}},Err(e)=>{let _=c.execute("UPDATE whatsapp_messages SET status='failed',error_text=?1 WHERE id=?2",params![e.to_string(),log_id]);Err(format!("Falha de conexão com WhatsApp API: {}",e))}}}

