import { invoke } from "@tauri-apps/api/core";

export type Client = { id:number; name:string; phone:string; birthDate:string; createdAt:string };
export type Service = { id:number; name:string; priceCents:number; durationMin:number; active:boolean };
export type Staff = { id:number; name:string; phone:string; commissionPercent:number; productCommissionPercent:number; active:boolean; owner:boolean };
export type StaffServiceCommission = { staffId:number; serviceId:number; serviceName:string; commissionPercent:number };
export type StaffPerformance = { staffId:number; staffName:string; grossCents:number; commissionCents:number; netCents:number; serviceSales:number; productSales:number };
export type Appointment = { id:number; clientId:number|null; clientName:string; phone:string; staffId:number|null; staffName:string; serviceNames:string; date:string; time:string; durationMin:number; totalCents:number; status:string; paymentMethod:string; note:string; cashTransactionId:number|null; createdAt:string };
export type Availability = { durationMin:number; totalCents:number; availableTimes:string[] };
export type CashTransaction = { id:number; kind:string; description:string; amountCents:number; date:string; paymentMethod:string; clientId:number|null; staffId:number|null; staffName:string; source:string; saleType:string; commissionPercent:number; commissionCents:number; netCents:number };
export type Product = { id:number; name:string; description:string; priceCents:number; stock:number; active:boolean };
export type MonthSummary = { month:number; incomeCents:number; expenseCents:number; balanceCents:number; transactions:number };
export type MonthlyReport = { year:number; months:MonthSummary[]; yearIncomeCents:number; yearExpenseCents:number; yearBalanceCents:number };
export type Health = { storageMode:string; databasePath:string; schemaVersion:number };
export type BusinessSettings = { businessName:string; ownerName:string; phone:string; whatsapp:string; address:string; logoPath:string; currency:string; timezone:string; backupDestination:string; configured:boolean };
export type BackupItem = { fileName:string; path:string; sizeBytes:number; createdAt:string };
export type MaintenanceReport = { integrity:string; databaseSizeBytes:number; schemaVersion:number; storageMode:string; databasePath:string; lastBackup:string };
export type MaintenanceCheck = { key:string; label:string; status:"ok"|"warning"|"error"|string; detail:string; repairable:boolean };
export type MaintenanceDiagnosis = { overallStatus:"ok"|"warning"|"error"|string; checks:MaintenanceCheck[]; recommendedActions:string[] };
export type RepairAction = "checkpoint"|"reindex"|"optimize"|"vacuum"|"repair_cash"|"repair_stock"|"repair_commissions"|"repair_appointment_links"|"standard_repair";
export type RepairResult = { action:string; success:boolean; message:string; safetyBackup:string };
export type OpeningHour = { dayOfWeek:number; startTime:string; endTime:string; enabled:boolean };
export type RemarketingClient = { id:number; name:string; phone:string; lastVisit:string; daysWithoutVisit:number; totalSpentCents:number; visits:number };
export type ArchivedItem = { id:number; name:string; kind:"client"|"service"|"staff"|"product"|string };
export type WhatsAppSettings = { enabled:boolean; apiBaseUrl:string; apiVersion:string; phoneNumberId:string; accessToken:string; socialLinksText:string };
export type WhatsAppSendResult = { success:boolean; providerMessageId:string; status:string };

export const desktopApi = {
 health:()=>invoke<Health>("health"),
 clients:()=>invoke<Client[]>("list_clients"),
 createClient:(input:{name:string;phone:string;birthDate?:string})=>invoke<Client>("create_client",{input}),
 updateClient:(input:{id:number;name:string;phone:string;birthDate?:string})=>invoke<void>("update_client_record",{input}),
 setClientActive:(id:number,active:boolean)=>invoke<void>("set_client_active",{id,active}),
 deleteClient:(id:number)=>invoke<void>("delete_client_safe",{id}),
 services:()=>invoke<Service[]>("list_services"),
 createService:(input:{name:string;priceCents:number;durationMin:number})=>invoke<Service>("create_service",{input}),
 updateService:(input:{id:number;name:string;priceCents:number;durationMin:number})=>invoke<void>("update_service_record",{input}),
 setServiceActive:(id:number,active:boolean)=>invoke<void>("set_service_active",{id,active}),
 deleteService:(id:number)=>invoke<void>("delete_service_safe",{id}),
 staff:()=>invoke<Staff[]>("list_staff"),
 createStaff:(input:{name:string;phone?:string;commissionPercent?:number;productCommissionPercent?:number;owner?:boolean})=>invoke<Staff>("create_staff",{input}),
 updateStaff:(input:{id:number;name:string;phone?:string;commissionPercent:number;productCommissionPercent:number})=>invoke<void>("update_staff_record",{input}),
 setStaffActive:(id:number,active:boolean)=>invoke<void>("set_staff_active",{id,active}),
 deleteStaff:(id:number)=>invoke<void>("delete_staff_safe",{id}),
 staffServiceCommissions:(staffId:number)=>invoke<StaffServiceCommission[]>("list_staff_service_commissions",{staffId}),
 setStaffServiceCommission:(input:{staffId:number;serviceId:number;commissionPercent:number})=>invoke<void>("set_staff_service_commission",{input}),
 staffPerformance:(start?:string,end?:string)=>invoke<StaffPerformance[]>("staff_performance",{start:start||null,end:end||null}),
 availability:(input:{date:string;serviceIds:number[];staffId:number|null})=>invoke<Availability>("availability",{input}),
 appointments:(date?:string)=>invoke<Appointment[]>("list_appointments",{date:date||null}),
 createAppointment:(input:{clientId:number|null;clientName:string;phone:string;staffId:number|null;serviceIds:number[];date:string;time:string;note?:string})=>invoke<Appointment>("create_appointment",{input}),
 editAppointment:(input:{id:number;clientId:number|null;clientName:string;phone:string;staffId:number|null;serviceIds:number[];date:string;time:string;note?:string})=>invoke<void>("edit_appointment_full",{input}),
 updateAppointment:(input:{id:number;status:string;paymentMethod?:string;note?:string})=>invoke<void>("update_appointment",{input}),
 cashTransactions:(start?:string,end?:string)=>invoke<CashTransaction[]>("list_cash_transactions",{start:start||null,end:end||null}),
 createCashTransaction:(input:{kind:"entrada"|"despesa";description:string;amountCents:number;date:string;paymentMethod?:string;clientId?:number|null;staffId?:number|null;saleType?:"service"|"product"|"other";serviceId?:number|null;productId?:number|null;quantity?:number})=>invoke<CashTransaction>("create_cash_transaction",{input}),
 updateCashTransaction:(input:{id:number;description:string;amountCents:number;date:string;paymentMethod?:string;clientId?:number|null;staffId?:number|null})=>invoke<void>("update_cash_record",{input}),
 voidCashTransaction:(id:number,reason:string)=>invoke<number>("void_cash_record",{id,reason}),
 monthlyReport:(year:number)=>invoke<MonthlyReport>("monthly_report",{year}),
 products:()=>invoke<Product[]>("list_products"),
 createProduct:(input:{name:string;description?:string;priceCents:number;stock:number})=>invoke<Product>("create_product",{input}),
 updateProduct:(input:{id:number;name:string;description?:string;priceCents:number})=>invoke<void>("update_product_record",{input}),
 setProductActive:(id:number,active:boolean)=>invoke<void>("set_product_active",{id,active}),
 deleteProduct:(id:number)=>invoke<void>("delete_product_safe",{id}),
 adjustStock:(input:{productId:number;quantity:number;note?:string})=>invoke<void>("adjust_stock",{input}),
 archivedItems:(kind:"client"|"service"|"staff"|"product")=>invoke<ArchivedItem[]>("archived_items",{kind}),
 restoreArchived:(kind:"client"|"service"|"staff"|"product",id:number)=>invoke<void>("restore_archived",{kind,id}),
 openingHours:()=>invoke<OpeningHour[]>("list_opening_hours_cmd"),
 saveOpeningHours:(rows:OpeningHour[])=>invoke<void>("save_opening_hours_cmd",{rows}),
 remarketingClients:(minimumDays:number,referenceDate:string)=>invoke<RemarketingClient[]>("remarketing_clients",{minimumDays,referenceDate}),
 whatsAppSettings:()=>invoke<WhatsAppSettings>("get_whatsapp_settings"),
 saveWhatsAppSettings:(input:WhatsAppSettings)=>invoke<WhatsAppSettings>("save_whatsapp_settings",{input}),
 sendWhatsAppText:(clientId:number|null,phone:string,messageType:string,text:string)=>invoke<WhatsAppSendResult>("send_whatsapp_text",{clientId,phone,messageType,text}),
 businessSettings:()=>invoke<BusinessSettings>("get_business_settings"),
 saveBusinessSettings:(input:BusinessSettings)=>invoke<BusinessSettings>("save_business_settings",{input}),
 backups:()=>invoke<BackupItem[]>("list_backups"),
 createBackup:()=>invoke<BackupItem>("create_backup"),
 restoreBackup:(path:string)=>invoke<void>("restore_backup",{path}),
 maintenanceReport:()=>invoke<MaintenanceReport>("maintenance_report"),
 maintenanceDiagnosis:()=>invoke<MaintenanceDiagnosis>("maintenance_diagnosis"),
 runMaintenanceRepair:(action:RepairAction)=>invoke<RepairResult>("run_maintenance_repair",{action}),
 writeSupportReport:()=>invoke<string>("write_support_report"),
};
